/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.108
 * Generated at: 2025-09-16 03:52:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;
import java.text.SimpleDateFormat;

public final class Join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("/* 전역 스타일 */\r\n");
      out.write("*{\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("    background: linear-gradient(to right, #ACB6E5, #74ebd5);\r\n");
      out.write("    font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 제목 스타일 */\r\n");
      out.write("h2 {\r\n");
      out.write("    color: #333;\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 폼 컨테이너 */\r\n");
      out.write("form {\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    padding: 30px;\r\n");
      out.write("    border: 1px solid #e9ecef;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    width: 90%;\r\n");
      out.write("    max-width: 600px;\r\n");
      out.write("    margin: 20px auto;\r\n");
      out.write("    box-shadow: 0 4px 6px rgba(0,0,0,0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 테이블 스타일 (게시판 테이블과 유사하게) */\r\n");
      out.write("table {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    border-collapse: collapse;\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table td {\r\n");
      out.write("    padding: 12px 15px;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 입력 필드, 선택 박스 스타일 (검색 폼과 유사하게) */\r\n");
      out.write("input[type=\"text\"],\r\n");
      out.write("input[type=\"password\"],\r\n");
      out.write("input[type=\"file\"],\r\n");
      out.write("select {\r\n");
      out.write("    padding: 8px 12px;\r\n");
      out.write("    border: 1px solid #ced4da;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    color: #495057;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 라디오 버튼, 체크박스 스타일 */\r\n");
      out.write("input[type=\"radio\"],\r\n");
      out.write("input[type=\"checkbox\"] {\r\n");
      out.write("    width: auto;\r\n");
      out.write("    margin-right: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 버튼 스타일 (게시판 글쓰기, 검색 버튼과 유사하게) */\r\n");
      out.write("input[type=\"button\"],\r\n");
      out.write("input[type=\"reset\"],\r\n");
      out.write("button {\r\n");
      out.write("    padding: 8px 16px;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    background-color: #4CAF50;\r\n");
      out.write("    color: white;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    transition: background-color 0.3s ease;\r\n");
      out.write("    margin-right: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"button\"]:hover,\r\n");
      out.write("input[type=\"reset\"]:hover,\r\n");
      out.write("button:hover {\r\n");
      out.write("    background-color: #0056b3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

  Date today = new Date(); // 현재 날짜와 시간 객체 생성
  SimpleDateFormat yearFormat = new SimpleDateFormat("yyyy"); // 년도 형식 지정
  String year = yearFormat.format(today); // 년도만 추출
  int intyear = Integer.parseInt(year);

      out.write("\r\n");
      out.write("	\r\n");

	String loginerr = request.getParameter("loginerr");
	if (loginerr != null) out.print("비밀번호가 일치하지 않습니다.");

      out.write("\r\n");
      out.write("\r\n");
      out.write("	<form name=\"join_form\" action=\"Join_proc.jsp\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("		<h2>회 원 가 입</h2>\r\n");
      out.write("		<table>\r\n");
      out.write("		<tr>\r\n");
      out.write("		<td>아이디</td>\r\n");
      out.write("		<td><input type=\"text\" name=\"uid\" id=\"uid\" onkeyup=\"id_check()\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		<tr>\r\n");
      out.write("		<td colspan=\"2\" style=\"text-align: center;\"><span id=\"id_msg\"></span></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		<tr>\r\n");
      out.write("		<td>비밀번호</td>\r\n");
      out.write("		<td><input type=\"password\" name=\"upass1\" id=\"upass1\" onkeyup=\"pass_check()\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		<tr>\r\n");
      out.write("		<td>비밀번호 확인</td>\r\n");
      out.write("		<td><input type=\"password\" name=\"upass2\" id=\"upass2\" onkeyup=\"pass_check()\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		<tr>\r\n");
      out.write("		<td colspan=\"2\" style=\"text-align: center;\"><span id=\"pass_msg\"></span></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		<tr>\r\n");
      out.write("		<td>이름</td>\r\n");
      out.write("		<td><input type=\"text\" name=\"uname\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		<tr>\r\n");
      out.write("		<td>성별</td>\r\n");
      out.write("		<td><input type=\"radio\" name=\"sex\" value=\"M\" checked=\"checked\">남자\r\n");
      out.write("			<input type=\"radio\" name=\"sex\" value=\"F\">여자</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		<tr>\r\n");
      out.write("		<td>생일</td>\r\n");
      out.write("		<td>\r\n");
      out.write("		<select name=\"yyyy\">\r\n");
      out.write("		");
 
			for (int i=1950; i<=intyear; i++) {
		
      out.write("\r\n");
      out.write("				<option value=\"");
      out.print( i );
      out.write('"');
      out.write('>');
      out.print( i );
      out.write(" 년</option>\r\n");
      out.write("		");

			}
		
      out.write("\r\n");
      out.write("		</select><br><br>\r\n");
      out.write("		\r\n");
      out.write("		<select name=\"mm\">\r\n");
      out.write("		");
 
			for (int i=1; i<=12; i++) {
		
      out.write("\r\n");
      out.write("				<option value=\"");
      out.print( i );
      out.write("\">\r\n");
      out.write("										");
 if (i < 10) { 
      out.write("\r\n");
      out.write("											0");
      out.print( i );
      out.write(" 월\r\n");
      out.write("										");
 } else { 
      out.write("\r\n");
      out.write("											");
      out.print( i );
      out.write(" 월\r\n");
      out.write("										");
 } 
      out.write("\r\n");
      out.write("				</option>\r\n");
      out.write("		");

			}
		
      out.write("\r\n");
      out.write("		</select><br><br>\r\n");
      out.write("		\r\n");
      out.write("		<select name=\"dd\">\r\n");
      out.write("		");
 
			for (int i=1; i<=31; i++) {
		
      out.write("\r\n");
      out.write("				<option value=\"");
      out.print( i );
      out.write("\">\r\n");
      out.write("										");
 if (i < 10) { 
      out.write("\r\n");
      out.write("											0");
      out.print( i );
      out.write(" 일\r\n");
      out.write("										");
 } else { 
      out.write("\r\n");
      out.write("											");
      out.print( i );
      out.write(" 일\r\n");
      out.write("										");
 } 
      out.write("\r\n");
      out.write("				</option>\r\n");
      out.write("		");

			}
		
      out.write("\r\n");
      out.write("		</select>\r\n");
      out.write("		</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		<tr>\r\n");
      out.write("		<td>취미</td>\r\n");
      out.write("		<td><input type=\"checkbox\" name=\"hobby\" value=\"football\">축구\r\n");
      out.write("			<input type=\"checkbox\" name=\"hobby\" value=\"basketball\">농구\r\n");
      out.write("			<input type=\"checkbox\" name=\"hobby\" value=\"Volleyball\">배구</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		<tr>\r\n");
      out.write("		<td>사진</td>\r\n");
      out.write("		<td><input type=\"file\" name=\"upfile\" accept=\".gif, .jpg, .png\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("\r\n");
      out.write("		<tr>\r\n");
      out.write("		<td colspan=\"2\" style=\"text-align: center;\">\r\n");
      out.write("			<input type=\"button\" value=\"가입\" onclick=\"submit_check()\">\r\n");
      out.write("			<input type=\"reset\" value=\"리셋\">\r\n");
      out.write("			<button type=\"button\" onclick=\"history.back()\">취소</button>\r\n");
      out.write("		</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		</table>\r\n");
      out.write("	</form>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function submit_check() {\r\n");
      out.write("	var uid = document.getElementById(\"uid\");\r\n");
      out.write("	var upass1 = document.getElementById(\"upass1\");\r\n");
      out.write("	var upass2 = document.getElementById(\"upass2\");\r\n");
      out.write("	   	if(uid.value.trim().length < 4 ){\r\n");
      out.write("	      	alert('아이디가 너무 짧습니다.');\r\n");
      out.write("	      	uid.focus();\r\n");
      out.write("	      	return;\r\n");
      out.write("	   	}else if (upass1.value.trim().length < 4 || upass2.value.trim().length < 4) {\r\n");
      out.write("	   		alert('비밀번호가 너무 짧습니다.');\r\n");
      out.write("	   		upass1.focus();\r\n");
      out.write("	      	return;\r\n");
      out.write("	   	}else if (upass1.value !== upass2.value) {\r\n");
      out.write("	   		alert('비밀번호가 서로 다릅니다.');\r\n");
      out.write("	   		upass1.focus();\r\n");
      out.write("	      	return;\r\n");
      out.write("	   	}else {\r\n");
      out.write("			document.join_form.submit();\r\n");
      out.write("		}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function id_check()\r\n");
      out.write("{\r\n");
      out.write("   var uid = $('#uid').val();\r\n");
      out.write("   \r\n");
      out.write("   if(uid.length < 4)\r\n");
      out.write("   {\r\n");
      out.write("      return;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   $.ajax({\r\n");
      out.write("      url : \"./Join_check.jsp\",\r\n");
      out.write("      type : \"post\",\r\n");
      out.write("      data : {uid: uid},\r\n");
      out.write("      dataType : 'html',\r\n");
      out.write("      success : function(result){\r\n");
      out.write("         \r\n");
      out.write("         var data = result.trim();\r\n");
      out.write("         \r\n");
      out.write("         if(data == \"Y\")\r\n");
      out.write("         {\r\n");
      out.write("            var msg = \"<font color='blue'>아이디 사용 가능</font>\";\r\n");
      out.write("            $('#id_msg').html(msg);\r\n");
      out.write("         }\r\n");
      out.write("         else\r\n");
      out.write("         {\r\n");
      out.write("            var msg = \"<font color='red'>아이디 사용 불가</font>\";\r\n");
      out.write("            $('#id_msg').html(msg);\r\n");
      out.write("         }\r\n");
      out.write("      },\r\n");
      out.write("      error: function (request, status, error) {\r\n");
      out.write("           console.log(\"code: \" + request.status)\r\n");
      out.write("           console.log(\"message: \" + request.responseText)\r\n");
      out.write("           console.log(\"error: \" + error);\r\n");
      out.write("       }\r\n");
      out.write("   });\r\n");
      out.write("   return;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function pass_check() {\r\n");
      out.write("	var pass1 = $('#upass1').val();\r\n");
      out.write("	var pass2 = $('#upass2').val();\r\n");
      out.write("	\r\n");
      out.write("	if(pass1.length < 4 || pass2.length < 4)\r\n");
      out.write("	   {\r\n");
      out.write("			return;\r\n");
      out.write("	   }\r\n");
      out.write("	\r\n");
      out.write("	if (pass1 == pass2) {\r\n");
      out.write("		$('#pass_msg').html(\"<font color='blue'>비밀번호 확인됨</font>\");\r\n");
      out.write("	}else {\r\n");
      out.write("		$('#pass_msg').html(\"<font color='red'>비밀번호 서로 다름</font>\");\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
